### ISSUE TITLE
Failure to join tables with encrypted data - different number of partitions

### ISSUE THREAD

**Issue by oshritf** [ucbrise/opaque#34]
When performing join on encrypted data (Opaque) with another dataframe - there is a rdd.zip exception when the two dataframes are not with the same number of partitions. 

Caused by: java.lang.IllegalArgumentException: Can't zip RDDs with unequal numbers of partitions: List(3, 1)
        at org.apache.spark.rdd.ZippedPartitionsBaseRDD.getPartitions(ZippedPartitionsRDD.scala:57)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1930)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1134)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousUnionExec$$anonfun$executeBlocked$3.apply$mcJ$sp(operators.scala:346)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousUnionExec$$anonfun$executeBlocked$3.apply(operators.scala:346)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousUnionExec$$anonfun$executeBlocked$3.apply(operators.scala:346)
        at edu.berkeley.cs.rise.opaque.Utils$.time(Utils.scala:93)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousUnionExec.executeBlocked(operators.scala:346)
        at edu.berkeley.cs.rise.opaque.execution.EncryptedSortExec.executeBlocked(EncryptedSortExec.scala:33)
        at edu.berkeley.cs.rise.opaque.execution.EncryptedSortMergeJoinExec.executeBlocked(operators.scala:296)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousProjectExec.executeBlocked(operators.scala:207)
        at edu.berkeley.cs.rise.opaque.execution.OpaqueOperatorExec$class.executeCollect(operators.scala:147)
        at edu.berkeley.cs.rise.opaque.execution.ObliviousProjectExec.executeCollect(operators.scala:200)
        at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2193)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
        at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2546)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2192)
        at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2197)
        at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2197)
        at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2559)
        at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2197)
        at org.apache.spark.sql.Dataset.collect(Dataset.scala:2173)
      

Also, Opaque rdd partitions count always returns 0.

Regular join (on non-encrypted data) works well on the same data set.

To reproduce perform a simple join on two dataframes with different partitions size.
for example, using the person dataset provided in previous join issue:
- Use person.json or any input json file with multiple lines
- Create a new json file with a subset of the above (few lines)
- place the two files in the same folder
- Using spark shell, load the files into df using *
- load the subset into another df
- perform join on the two dataframes using the PersonID col - the results is the subset (with each dataframe having different # of partitions)
- perform the same join on encrypted data - rdd.zip error

**Comment by oshritf** [comment]
# 35

**Comment by oshritf** [comment]
#35

**Comment by chester-leung** [comment]
Hi @oshritf , I'm taking a look at this issue right now, but am unable to reproduce. Below is what I tried in the Spark shell:

```
scala> import edu.berkeley.cs.rise.opaque.implicits._
import edu.berkeley.cs.rise.opaque.implicits._

scala> edu.berkeley.cs.rise.opaque.Utils.initSQLContext(spark.sqlContext)

scala> val df1 = spark.read.json("person.json")
df1: org.apache.spark.sql.DataFrame = [DateOfBirth: string, EmailAddress: string ... 6 more fields]

scala> val df1_repart = df1.repartition(5)
df1_repart: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [DateOfBirth: string, EmailAddress: string ... 6 more fields]

scala> df1_repart.rdd.getNumPartitions
res1: Int = 5

scala> val df1_repart_enc = df1_repart.encrypted
df1_repart_enc: org.apache.spark.sql.DataFrame = [DateOfBirth: string, EmailAddress: string ... 6 more fields]

scala> val df2 = spark.read.json("idlist.json")
df2: org.apache.spark.sql.DataFrame = [PersonId: bigint]

scala> val df2_repart = df2.repartition(3)
df2_repart: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [PersonId: bigint]

scala> df2_repart.rdd.getNumPartitions
res2: Int = 3

scala> val df2_repart_enc = df2_repart.encrypted
df2_repart_enc: org.apache.spark.sql.DataFrame = [PersonId: bigint]

scala> df1_repart_enc.rdd.getNumPartitions
res3: Int = 0

scala> df1_repart_enc.repartition(5)
res4: org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [DateOfBirth: string, EmailAddress: string ... 6 more fields]

scala> df1_repart_enc.rdd.getNumPartitions
res5: Int = 0

scala> val unenc_join = df1_repart.join(df2_repart, Seq("PersonID"))
unenc_join: org.apache.spark.sql.DataFrame = [PersonID: bigint, DateOfBirth: string ... 6 more fields]

scala> val enc_join = df1_repart_enc.join(df2_repart_enc, Seq("PersonID"))
enc_join: org.apache.spark.sql.DataFrame = [PersonID: bigint, DateOfBirth: string ... 6 more fields] ```

Basically I:
* Created two dataframes with `spark.read.json()`
* Repartitioned one dataframe into 5 partitions, and the other into 3
* Encrypted each dataframe
* Joined the two unencrypted dataframes on the `PersonID` col, which worked
* Joined the encrypted dataframes on the `PersonID` col, which also worked

Please let me know exactly what you did so I can try reproducing the error you got
